#!/usr/bin/env bash
# Installs Nginx with the following configurations:

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
